export const elements = {
    tabPromotion: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(10) > .ng-scope.ng-isolate-scope > .ng-isolate-scope  > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnShowItens: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    inputSearchPromotion: '.input-group-search > .ng-pristine',
    btnSelectSale: 'button[class="btn btn-exchange ng-binding"]',
    btnCreatePromotion: '.btn-create',
    btnEditPromotion: ':nth-child(1) > :nth-child(6) > .flex > cp-edit-icon',
    btnDeletePromotion: '.flex > cp-delete-icon',
    inputNamePromotion: '.enable-enter > .mbg-input-wrapper > .ng-pristine',
    inputDateFinish: ':nth-child(3) > .mbg > :nth-child(2) > .gumga-date-input',
    inputPriceSheet: '.input-price-sheet > .mbg-select-wrapper > .mbg-select-input-fake',
    btnInputProduct: '.col-md-9 > .ng-pristine > .mbg-select-wrapper > .mbg-select-input-fake',
    inputProduct: '.mbg-select-list.active > .mbg-select-search-wrapper',
    btnAddProduct: '.btn',
    btnConsultProduct: '.btn-open-terminal',
    inputConsultProduct: '.flex > .input-terminal > .ng-empty',
    checkboxSelectProduct: '.list-cols > .col-action-select',
    inputValueProductPromotion: '.promotion-list-product-info > :nth-child(5) > .enable-enter > .mbg-input-money-wrapper > .ng-pristine', 
    inputValueProduct: '.promotion-list-product-info > :nth-child(4) > .enable-enter > .mbg-input-money-wrapper > .ng-pristine', 
    valuePercentageDicount: '.discount-percentage',
    btnFinishPromotion: '#id-save-promotion',
    btnClosedModalPromotion: '.m-t-44-b-24 > .col-md-12 > .cancel-link',
    btnLastPage: '.visible',
    btnConfirmDelete: '.confirm',
    btnErasedStatusPromotion: ':nth-child(4) > .ng-untouched > .mbg-select-wrapper > .fa-times',
    inputStatusPromotion: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    statusUnactive: 'div[uib-tooltip="Inativa"]',
    percentageDiscountOnSale: '.discount-value',
    btnErasedSearchFor: '.col-md-12 > .row > .col-md-3 > .ng-untouched > .mbg-select-wrapper > .fa-times',
    inputSearchFor: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    
    

}