export const elements = {
    tabProduct: ':nth-child(1) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(1) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    inputSearch: '.input-group-search > .ng-empty',
    btnOption: 'a[class="title-option dropdown-toggle"]',
    btnDetails: 'i[class="ng-scope fas fa-external-link-alt"]',
    divCurrentStock: ':nth-child(1) > :nth-child(5) > .stock-info',
    btnRegister: '.btn-create',
    inputCategory: '.mbg-product-tree > .mbg-select-wrapper > .mbg-select-input-fake > .place',
    inputModel: ':nth-child(1) > #entityModel > .mbg-select-wrapper > .mbg-select-input-fake',
    inputBrand: ':nth-child(2) > .enable-enter > .mbg-select-wrapper > .mbg-select-input-fake',
    inputCost: '.cost-value > .enable-enter > .mbg-input-money-wrapper > .ng-pristine',
    inputValue: ':nth-child(3) > .enable-enter > .mbg-input-money-wrapper > .ng-pristine',
    inputUnit: '.product-side-session-wrapper > :nth-child(1) > .col-md-12 > .ng-isolate-scope.ng-empty > .mbg-select-wrapper > .mbg-select-input-fake',
    btnAddSize: '.add-size > .ng-isolate-scope > .select-details-wrapper > .ng-details-wrapper > .chat-input-tool',
    btnAddColor: '.add-color > .ng-isolate-scope > .select-details-wrapper > .ng-details-wrapper > .chat-input-tool',
    btnSize: '.add-size > .ng-isolate-scope > .select-details-wrapper > .ng-details-wrapper > .intercom-composer-popover > .intercom-details-picker > .intercom-composer-popover-body-container > .intercom-composer-popover-body > .intercom-details-picker-groups > .intercom-details-picker-group > .content-details > :nth-child(2)',
    btnColorBlack: '.add-color > .ng-isolate-scope > .select-details-wrapper > .ng-details-wrapper > .intercom-composer-popover > .intercom-details-picker > .intercom-composer-popover-body-container > .intercom-composer-popover-body > .intercom-details-picker-groups > .intercom-details-picker-group > .content-details > :nth-child(34)',
    tabMatriz: '[index="2"] > .nav-link > .mb-fiscal-step-wrapper',
    inputStockP: ':nth-child(2) > .grid-product-edit-wrapper > .grid-product-stock',
    inputStockM: ':nth-child(3) > .grid-product-edit-wrapper > .grid-product-stock',
    inputStockG: ':nth-child(4) > .grid-product-edit-wrapper > .grid-product-stock',
    btnEdit: 'cp-edit-icon.ng-scope > svg',
    btnOptionDelete: 'i[class="ng-scope far fa-trash-alt"]',
    btnRemoveItem: 'a[class="link ng-binding"]',
    messageAlert:'div[class="mb-n-text ng-binding"]', 
    checkHaveDetails: '.col-md-8 > .green',
    optionShowInputStock: '[ng-show="$ctrl.enableTitle"] > .col-md-12 > .flex > .fa-plus-circle',
    inputStockNoDetails: '.col-md-4.ng-binding > .enable-enter > .mbg-input-number-wrapper > .ng-pristine',
    //Repasse
    btnOptionsTabProduct: 'mbg-dropdown',
    btnOptionchangeData: ':nth-child(8) > a',
    btnInputField: '.condition-item > .row > :nth-child(1) > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake',
    inputField: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    btnInputComparison: '.condition-item > .row > :nth-child(2) > .ng-pristine > .mbg-select-wrapper > .mbg-select-input-fake',
    btnInputValue: '.col-md-3.ng-scope > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake',
    btnInputApplyItem: '.apply-item > .row > :nth-child(1) > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake',
    btnInputApplyValue: '.col-md-4 > .ng-untouched > .mbg-select-wrapper > .mbg-select-input-fake',
    btnConfirmChangeData: '.mbg-btn-form-wrapper > button',
}