export const elements = {
    //Tela de inicio da venda e insercao dos produtos
    tabBudget: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(7) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnShowItens: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    eraseNameClient: '.mbg-select-person-wrapper > .ng-isolate-scope > .mbg-select-wrapper > .fa-times',
    inputClient: '.mbg-select-person-wrapper > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake > .place',
    btnInputEmployee: ':nth-child(2) > .ng-isolate-scope > .mbg-select-wrapper > .fa-caret-down',
    inputEmployee: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    btnInputGuide: '.col-md-8 > .row > :nth-child(1) > .ng-isolate-scope > .mbg-select-wrapper > .fa-caret-down',
    inputGuide:'.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    inputProduct: '.product-item-search-wrapper > .input-terminal > .search-text',
    btnConsultProduct: '[ng-click="$ctrl.openTerminal()"]',
    inputConsultProduct: '.flex > .input-terminal > .ng-empty',
    checkboxSelectProduct: '.list-cols > .col-action-select',
    btnSaveBudget:'button[class="btn finish make-consignment"]',
    msgSuccess: '.mb-n-text',
    checkboxPersonAuthorized: 'div[class="checkbox"]',
    spanPersonAuthorized: '[ng-show="$ctrl.movement.thirdiesAuthorized && $ctrl.movement.thirdiesAuthorized.name"] > .mbg-label',
    btnOptionProduct: '.summary-movement-options > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg',
    btnOptionDiscountInProduct: '.summary-movement-options > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(1) > a',
    inputPercentageDiscountInProduct: '.movement-percentage > .mbg-input-wrapper > .ng-pristine',
    btnContinueApplyDiscount:'.btn-next',
    valueTotalBudgetInProduct: '.info > h3.ng-binding',
    valueProductBeforeDiscount: '.summary-movement-right > [ng-show="!$ctrl.showQtdGift && !$ctrl.conferenceCheck"] > .minimal-value',
    haveLimit: '[ng-show="$ctrl.percentage < 1 && $ctrl.discountLimit && $ctrl.percentage > $ctrl.discountLimit"]',
    valueEmploy: ':nth-child(2) > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake > .mbg-select-value' ,
    btnHistoric: '',
    btnOptionHistoric: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg',
    btnCancel: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(3) > a',
    btnConfirmCancel: '.confirm',
    inputMotiveCancel: 'fieldset > input',
    btnBilling: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(1) > a',
    btnEdit: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(2) > a',
    eraseEmploy:':nth-child(2) > .ng-isolate-scope > .mbg-select-wrapper > .fa-times',
}