export const elements = {
    //parte fechar e abrir caixa
    tabCashier: '.caixa-aberto',
    btnConfer: '.check-entrys-account-header > .check-content',
    checkboxHaveChange: '.flex > .ng-isolate-scope',
    inputChange: '#change-money',
    selectCashier: '.mbg-select-wrapper > .fa-caret-down',
    inputChangeOpen: '.mbg-input-money-wrapper > .ng-pristine',
    valueChangeOpen: '.mbg-input-money-wrapper > .ng-valid',
    valueEmployeOpen: '[ng-show="$ctrl.entity.employee != null && !$ctrl.alreadyOpen && $ctrl.groupUnit && !$ctrl.loadingPdv"] > :nth-child(2) > :nth-child(2)',
    valueDateHourOpen: ':nth-child(2) > .col-md-2',
    //parte movimentacao de caixa
    btnShowItens: ':nth-child(7) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    tabMovementCashier: ':nth-child(7) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(4) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnSelectOrigin: '.col-md-6.ng-scope > .ng-untouched > .mbg-select-wrapper > .fa-caret-down',
    btnSelectFinancialCategory: '.enable-enter > .mbg-select-wrapper > .fa-caret-down',
    inputValue: '.mbg-input-money-wrapper > .ng-pristine',
    inputObservation: '.mbg-text-wrapper > .ng-pristine',
    btnConinueMovementCashier: '.mbg-btn-form-wrapper > button',
    receipt: '.report-iframe',
    btnSelectDestiny: '.ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake',
    btnChangeTab: '.mb-smqm-button-arrow-container',
    //parte transferencia 
    btnShowItensBanking: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    tabTransfer: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(6) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnSelectOriginTransfer: ':nth-child(1) > .ng-untouched > .mbg-select-wrapper > .mbg-select-input-fake',
    btnSelectDestinyTransfer: ':nth-child(2) > .ng-isolate-scope > .mbg-select-wrapper > .mbg-select-input-fake',
    inputOriginTransfer: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    inputValueTransfer: '.mbg-input-money-wrapper > .ng-pristine',
    inputHistoricTransfer: '.mbg-text-wrapper > .ng-pristine',
    btnSaveTransfer: '.mbg-btn-form-wrapper > button',
    msgTransfer: '.mb-n-inside-container',
    //parte conciliacao de cartao
    tabCardReconciliation: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(1) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    inputStarDate: '.mbg-date-between-start',
    inputEndDate: '.mbg-date-between-end',
    btnSelectCardMachine: '.mbg-select-wrapper > .fa-caret-down',
    btnSearchCardReconciliation: '.btn-create',
    btnConfer: '.check-entrys-account-header > .check-content',
    btnConciliate: '.mbg-btn-form-wrapper > button',
    //Pare fechamento de comissão
    tabComissionClosed: ':nth-child(7) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(2) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnEmploy: '.mbg-select-input-fake',
    inputEmploy: '.mbg-select-search-wrapper > .ng-pristine',
    btnProcessComission: '.mbg-btn-form-wrapper > button',
    btnGenerateAccount: '.btn-save > .mbg-btn-form-wrapper > button',
    inputDue: '.close-content > .mbg > :nth-child(2) > .gumga-date-input',
    btnFinishComissionClosed: '.close-content > .btn-save > .mbg-btn-form-wrapper > button',

}