export const elements = {
    tabReceipt: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(1) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    inputProvider: '.place',
    btnStartReceipt: '.mbg-btn-form-wrapper > button',
    inputProduct: '.search-text',
    inputQuantity: '#qtdItem > .mbg-input-number-wrapper > .ng-valid',
    btnAddProduct: '.btn-update-list',
    btnFinishReceipt: '.mbg-btn-form-wrapper > button',
    bntNotGenerateTitles: '.bt-next > .cancel-link',
    inputParcelsTitle: ':nth-child(2) > .ng-isolate-scope > .mbg-input-number-wrapper > .ng-pristine',
    btnGenerateTitles: '.btn-finish-generate-title > .mbg-btn-form-wrapper > button',
    selectTypeOperation: ':nth-child(4) > .input-wrapper',
    numberNoteReceipt: ':nth-child(1) > :nth-child(3) > .tooltip-nfe > :nth-child(1)',
    bntClosedInvoices: '.mbg-close-modal > .fas',
    btnConsultProduct: '.btn-open-terminal',
    inputConsultProduct: '.flex > .input-terminal > .ng-empty',
    checkboxSelectProduct: '.list-cols > .col-action-select',
    tabStockOut: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(3) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    inputClient: '.place',
    btnStartStockOut: '.mbg-btn-form-wrapper > button',
    btnFinishStockOut: '.mbg-btn-form-wrapper > button',
    btnSendNfe: '#emitirNfe',
    btnSendNfce: '#emitirNfce',
    printInvoice: '[index="1"] > .modal-dialog > .modal-content > .ma-container > .mbg-modal',
    btnShowItens: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    tabStockTransfer: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(5) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnSelectBranch: '.mbg-select-input-fake',
    btnStartTransfer: '.mbg-btn-form-wrapper > button',
    inputBranches: '.mbg-select-search-wrapper > .ng-pristine',
    optionBranches: '.ul-options > :nth-child(2) > .ng-scope',
    btnFinishTransfer: '.mbg-btn-form-wrapper > button',
    btnHistoricTransfer: 'a > span',
    filterStatus: '.input-wrapper > .ng-pristine',
    btnOptionTransfer: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg',
    btnAcceptTransfer: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(9) > a',
    btnFinishAcceptTransfer: '.mbg-btn-form-wrapper > button',
    btnRejectTransfer: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(10) > a',
    inputMotive: 'fieldset > input',
    tabInventory: ':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(6) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnCreateInventory: '.btn-create',
    SelectResponsible: '.ng-invalid > :nth-child(2) > :nth-child(1) > .ng-isolate-scope > .mbg-select-wrapper > .fa-caret-down',
    inputResponsible: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    btnContinueInventory: '.mbg-btn-form-wrapper > button',
    selectinputProductInventory: '.col-md-8 > .ng-untouched > .mbg-select-wrapper > .fa-caret-down',
    inputProductInventory: '.mbg-select-list.active > .mbg-select-search-wrapper',
    btnAddProductInventory: '.col-md-9 > .flex > .btn',
    btnCancelPrint: 'button[class="mbg-link-cancel ng-binding ng-scope"]',
    inputProductCollect: '[placeholder="Pesquisa por nome, referência ou código de barras e tecle ENTER"]',
    btnStartCollect: '.page-wrapper div[class="mbg-btn-form-wrapper"]',
    btnFinishCollect: '.mbg-btn-form-wrapper > button',
    inputDistribute: ':nth-child(5) > .mbg-input-wrapper > .ng-pristine',
    btnFinishDistribute: '.mbg-btn-form-wrapper > button',
    btnNotGenerateTitlesDistributes: '.bt-next > .cancel-link',
    btnGenerateTitlesDistributes: '.btn-finish-generate-title > .mbg-btn-form-wrapper > button',
    btnNotSendInvoice: '.mbg-group-buttons.ng-scope > :nth-child(3) > .mbg-link-cancel',
    btnSendInvoice:':nth-child(1) > .btn-confirm-alert',
    btnSendAndPrintInvoice: ':nth-child(2) > .btn-confirm-alert',
    btnCompany: '.mb-tu-button-title',
    btnOtionCompany: '.body-company > :nth-child(2)',
    btnChangeCompany: '.mb-tu-m-ca-btn',
    btnNotifications: '.mb > .far',
    btnRejectbyNotification: '[first="true"] > .notifition-item-wrapper > .notification-metadata > .notification-actions > :nth-child(3)',
    btnConfirmRejectByNotification: '[first="true"] > .notifition-item-wrapper > .notification-metadata > .notification-actions > .ng-binding',
    btnConfirmRejectByHistoric: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(11) > a',
    btnHistoric: '.links-wrapper > a:contains(Histórico)',
    btnOptionHistoric: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg > [cy="18"]',
    btnOptionChargebackReceipt: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(2) > a',
    btnConfirmChargebackAndGeneratedReceipt: '.confirm',
    btnOptionGenerateNewReceipt: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(5) > a',
    btnOptionDistribute: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(1) > a > .ng-binding',
    btnOptionXMl: '[index="2"] > .nav-link > .ng-scope',
    SelectXMl: 'input[type="file"]',
    btnContinueReceiptXML: '.mbg-btn-form-wrapper > button',
    btnContinueForDistribution: '.btn-update-list',
    btnProductReceiptXML: '[xml-item-index="0"] > .xml-item > .xml-col-name > .xml-link-item-wrapper > .ng-pristine > .mbg-select-wrapper > .mbg-select-input-fake',
    inputProductReceiptXML: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-valid',
    inputQuantityDistribution: ':nth-child(2) > .grid-product-edit-wrapper > .grid-product-stock',
    btnConclue: ':nth-child(3) > .col-md-12 > .flex-center > .ng-isolate-scope > .mbg-btn-form-wrapper > button',
    btnEditProduct: '[xml-item-index="0"] > .xml-item > .xml-col-name > .xml-link-item-wrapper > .flex > [ng-show="$row.product && $row.product.id && !$row.productAlreadyImported && !$ctrl.isSharedRecord($row.product)"]',
    btnFinishReceiptXML: '.mbg-btn-form-wrapper > button',
    btnOptionsInMoviment: '.title-option > svg',
    btnCancelInMoviment: '.dropdown-menu > :nth-child(2) > a',
    inputMotiveCancel:  'fieldset > input',
    btnConfirmCancel: '.confirm',
    btnOptionSaveMoviment: '.dropdown-menu > :nth-child(1) > a',
    btnCancelReceiptByHistoric: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(9) > a',
    btnMotiveCancelByHistoric: '.mbg-input-wrapper > .ng-pristine',
    btnEditReceipt: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(3) > a',
    btnEditStockOut:':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(3) > a',
    btnCancelStockOutByHistoric: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(9) > a',
    btnOptionHistoricStockOut: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg',
    btnChargebackStockOut:':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(2) > a',
    btnGenerateNewStockOut: ':nth-child(1) > :nth-child(11) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(5) > a',
    checkboxDistribute: 'input[type="checkbox"]',
    btnSaveTransferStock: '.save > a',
    btnOptionCancelTransfer: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(4) > a',
    btnOptionEditTransfer: ':nth-child(1) > :nth-child(9) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(2) > a',
    msgCancelTransfer: '.mb-n-text',
    btnSaveReceivedXML: '.save > a > .ng-binding',
    msgAlertDistribute: '.mb-n-inside-container',
    linkCreateNewProvider: '.relative > .ng-isolate-scope > .movement-preview-data-wrapper > .box > .link-new',
    tabDevolution:':nth-child(6) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(4) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnStartDevolution: '.mbg-btn-form-wrapper > button',
    btnFinishDevolution: '.mbg-btn-form-wrapper > button',
}