export const elements = {
    tabDevolution: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(6) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    btnShowItens: ':nth-child(2) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-seemore',
    btnInputClient: '.mbg-select-wrapper > .fa-caret-down',
    inputClient: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    btnSelectSale: 'button[class="btn btn-exchange ng-binding"]',
    checkboxCheckAll: '.label-cbx',
    btnGeneratesCoupons: '.mbg-btn-form-wrapper > button',
    btnReturnMoney: ':nth-child(2) > .exchange-give-back-button',
    btnComfirmReturnMoney:'.mbg-btn-form-wrapper > button',
    btnInputEmployee: ':nth-child(2) > .ng-isolate-scope > .mbg-select-wrapper > .fa-caret-down',
    inputEmployee: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    bntClosedInvoices: '.mbg-close-modal > .fas',
    printCoupons: '.report-iframe',
    btnDevolutionWithoutInformingSale: '.btn-continue-without-sale',
    inputProduct: '.input-terminal > .search-text',
    btnConsultProduct: '.btn-open-terminal',
    inputConsultProduct: '.flex > .input-terminal > .ng-empty',
    checkboxSelectProduct: '.list-cols > .col-action-select',
    inputDevolutionCardPresent:'.mbg-input-wrapper > .ng-pristine', 
    btnContinueDevolution: '#btn-invoice-sale',
    btnHistoricDevolution: '.links-wrapper > a',
    valueDevolution: ':nth-child(1) > [style="text-align: right;"]',
    btnOptiondevolution: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .title-option > svg',
    btnOptionChargeback: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(3) > a',
    btnConfirmChargeback: '.btn-confirm-alert > .ng-binding',
    tabCashier: ':nth-child(7) > mb-sm-subcategory.ng-scope > [sm-sub-category=""] > .mg-smsc-container > :nth-child(1) > .ng-scope.ng-isolate-scope > .ng-isolate-scope > .link-with-icon > a.mb > .mb > .mb-smb-text',
    valueMoney: ':nth-child(5) > .ng-isolate-scope > .check-entrys-wrapper > .check-entrys-body > :nth-child(1) > .check-entrys-account-header > .check-entrys-account-metadata > label.ng-binding > .ng-binding',
    btnOptionAlterInformation: ':nth-child(1) > :nth-child(8) > .flex > .ng-isolate-scope > .mbg-dropdown-wrapper > .dropdown > .dropdown-menu > :nth-child(14) > a',
    btnEraseEmployDevolution: '[ng-model="$ctrl.vendorDevolutionModal"] > .mbg-select-person-wrapper > .ng-isolate-scope > .mbg-select-wrapper > .fa-times',
    inputEmployeDevolution: '.mbg-select-list.active > .mbg-select-search-wrapper > .ng-pristine',
    valueEmployeDevolution: 'tbody > :nth-child(1) > :nth-child(4)',
    

}